cargo-features = ["edition"]

[package]
name = "uefi-test-runner"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
uefi = { path = ".." }
uefi-services = { path = "../uefi-services" }
uefi-exts = { path = "../uefi-exts" }

log = { version = "0.4", default-features = false }
