[package]
name = "uefi-test-runner"
version = "0.2.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
uefi = { version = "0.4.2", features = ['exts'] }
uefi-services = "0.2.0"

log = { version = "0.4.8", default-features = false }

[features]
qemu = ["uefi-services/qemu"]
