sudo: false

# We need a newer version of Python
language: python

# Need Python for build script
python: 3.6

install:
  # Manually install nightly Rust
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - source "$HOME/.cargo/env"
  - rustc -V
  - cargo -V
  # Required by cargo-xbuild
  - rustup component add rust-src
  # Try installing cargo-xbuild if it's not already installed
  - hash cargo-xbuild || cargo install cargo-xbuild
  # Download OVMF
  - bash -e "uefi-test-runner/ci/ovmf.sh"

before_script:
  - export PATH="$PATH:$HOME/qemu/bin"
  - hash qemu-system-x86_64 || bash -e "uefi-test-runner/ci/travis-qemu.sh"
  - qemu-system-x86_64 --version

script:
  - cd uefi-test-runner && ./build.py run --headless
  - cd uefi-test-runner && ./build.py clippy

cache:
  directories:
    - $HOME/.cargo/
    - $HOME/qemu/
    - target/

addons:
  apt:
    packages:
      - bsdtar
