[workspace]
resolver = "2"
members = [
    "template",
    "uefi",
    "uefi-macros",
    "uefi-services",
    "uefi-test-runner",
    "xtask",
]

[patch.crates-io]
uefi = { path = "uefi" }
uefi-macros = { path = "uefi-macros" }
uefi-services = { path = "uefi-services" }
