[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.51"
clap = { version = "4.2.0", default-features = false, features = ["derive", "help", "usage", "std"] }
fatfs = { version = "0.3.6", default-features = false, features = ["alloc", "std"] }
fs-err = "2.6.0"
heck = "0.4.0"
itertools = "0.10.5"
mbrman = "0.5.1"
nix = { version = "0.26.1", default-features = false, features = ["fs"] }
os_info = { version = "3.6.0", default-features = false }
proc-macro2 = "1.0.46"
quote = "1.0.21"
regex = "1.5.4"
serde_json = "1.0.73"
syn = { version = "2.0.0", features = ["full"] }
tempfile = "3.5.0"
