[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.51"
clap = { version = "4.0.4", features = ["derive"] }
# The latest fatfs release (0.3.5) is old, use git instead to pick up some fixes.
fatfs = { git = "https://github.com/rafalh/rust-fatfs.git", rev = "87fc1ed5074a32b4e0344fcdde77359ef9e75432" }
fs-err = "2.6.0"
heck = "0.4.0"
itertools = "0.10.5"
# Use git as a temporary workaround for https://github.com/rust-osdev/uefi-rs/issues/573.
mbrman = { git = "https://github.com/cecton/mbrman.git", rev = "78565860e55c272488d94480e72a4e2cd159ad8e" }
nix = "0.26.1"
proc-macro2 = "1.0.46"
quote = "1.0.21"
regex = "1.5.4"
serde_json = "1.0.73"
syn = { version = "1.0.101", features = ["full"] }
tempfile = "3.2.0"
