[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.51"
clap = { version = "3.2.1", features = ["derive"] }
# The latest fatfs release (0.3.5) is old, use git instead to pick up some fixes.
fatfs = { git = "https://github.com/rafalh/rust-fatfs.git", rev = "87fc1ed5074a32b4e0344fcdde77359ef9e75432" }
fs-err = "2.6.0"
mbrman = "0.4.2"
nix = "0.25.0"
regex = "1.5.4"
serde_json = "1.0.73"
tempfile = "3.2.0"
