[package]
name = "uefi-services"
version = "0.4.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
edition = "2018"
description = "Higher-level utilities for uefi-rs"
repository = "https://github.com/rust-osdev/uefi-rs"
keywords = ["uefi", "efi"]
categories = ["embedded", "no-std", "api-bindings"]
license = "MPL-2.0"

[badges]
travis-ci = { repository = "rust-osdev/uefi-rs" }
is-it-maintained-issue-resolution = { repository = "rust-osdev/uefi-rs" }
is-it-maintained-open-issues = { repository = "rust-osdev/uefi-rs" }

[dependencies]
log = { version = "0.4.11", default-features = false }
cfg-if = "1.0.0"

[dependencies.uefi]
path = "../"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.13.1"

[features]
# Enable QEMU-specific functionality
qemu = []
no_panic_handler = []
