[package]
name = "uefi-services"
version = "0.21.0"
readme = "README.md"
description = "Higher-level utilities for the `uefi` crate."

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
uefi = { version = "0.24.0", features = ["global_allocator"] }
log.workspace = true
cfg-if = "1.0.0"
qemu-exit = { version = "3.0.1", optional = true }

[features]
default = ["panic_handler", "logger"]
# Enable QEMU-specific functionality
qemu = ["qemu-exit"]
panic_handler = []
logger = ["uefi/logger"]
