[package]
name = "uefi-services"
version = "0.17.0"
authors = ["The Rust OSDev team"]
readme = "README.md"
edition = "2021"
description = "Higher-level utilities for the `uefi` crate."
repository = "https://github.com/rust-osdev/uefi-rs"
keywords = ["uefi", "efi"]
categories = ["embedded", "no-std", "api-bindings"]
license = "MPL-2.0"
rust-version = "1.68"

[dependencies]
uefi = { version = "0.20.0", features = ["global_allocator"] }
log = { version = "0.4.5", default-features = false }
cfg-if = "1.0.0"
qemu-exit = { version = "3.0.1", optional = true }

[features]
default = ["panic_handler", "logger"]
# Enable QEMU-specific functionality
qemu = ["qemu-exit"]
panic_handler = []
logger = ["uefi/logger"]
