[package]
name = "uefi-raw"
version = "0.1.0"
authors = ["The Rust OSDev team"]
readme = "README.md"
edition = "2021"
description = "Raw UEFI types"
repository = "https://github.com/rust-osdev/uefi-rs"
keywords = ["uefi", "efi"]
categories = ["embedded", "no-std", "api-bindings"]
license = "MPL-2.0"
rust-version = "1.68"

[dependencies]
bitflags = "1.3.1"
ptr_meta = { version = "0.2.0", default-features = false }
uefi-macros = "0.11.0"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
